### ISSUE TITLE
Gamecube/Xbox pso ep1&2 support 

### ISSUE THREAD

**Issue by wangzhenxyz1** [dcrodman/archon#16]
plz support Gamecube/Xbox pso ep1&2

**Comment by dcrodman** [comment]
Hi @wangzhenxyz1, supporting Xbox is at this point far too difficult to be worth the effort since Sega discontinued those servers ages ago and I don't think enough people play on that platform to warrant it. I'd like to support Gamecube at some point but as I haven't yet implemented full support for PSOBB (which was my original intention) that's still the priority.

I'm going to close this for now, I want to keep the tracker for questions and smaller actionable tasks. I promise I'm aware of it and will look more seriously into supporting Gamecube as Archon matures.

**Comment by wangzhenxyz1** [comment]
cool, waiting for new features
