### ISSUE TITLE
Connection refused by shipgate server

### ISSUE THREAD

**Issue by Gamizard** [dcrodman/archon#61]
I've been trying to set up an Archon instance and can't get past this error on startup:
`error starting SHIP server: error initializing SHIP server: error registering with shipgate: twirp error internal: failed to do request: Post "https://<server>:13000/twirp/archon.Shipgate/RegisterShip": dial tcp <server>:13000: connect: connection refused`

I'm able to connect to the shipgate server through a web browser and netstat shows it as listening, no firewall is running on the server either so I'm not sure what's wrong.

**Comment by Gamizard** [comment]
Oddly, adding game files into the patches folder seems to fix this. It looks like the ship server is trying to connect to shipgate server before it's ready, causing the error.

**Comment by dcrodman** [comment]
Hard to say without seeing the log output but my assumption here is that I re-introduced a race condition while refactoring that I had previously guarded against with respect to shipgate startup. Adding files to the patches directory probably solves the issue because it slows down the patch server startup and given the [Controller initializes the servers sequentially](https://github.com/dcrodman/archon/blob/60bf189178e103294b14b78ff7c5698c402e2499/internal/controller.go#L136), the shipgate to finish initializing before other servers start connecting.

I'll see if I can reproduce this

**Comment by Gamizard** [comment]
I'm pretty sure on it being a race condition, yeah. While I don't have a log anymore, (I switched to using newserv) I do remember adding a time.Sleep() to the patch server making it work.

**Comment by Gamizard** [comment]
Accidental close.
